version: '2'

services:

#    oneshotqna:
#       image: dockerusername/host
#        build:
#            context: ./src
#            dockerfile: ./Dockerfile
#        ports:
#            - "9901:5000"
    summary:
        image: localhost:32000/summary
        build:
            context: ./src/summarization
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "8501:8501"
