apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: summary
  name: summary
spec:
  ports:
  - name: "8501"
    port: 8501
    targetPort: 8501
  selector:
    io.kompose.service: summary
status:
  loadBalancer: {}
